### ISSUE TITLE
setting open_revs causes error

### ISSUE THREAD

**Issue by thigg** [IBM/cloudant-java-sdk#103]
**Describe the bug**
if you set open revs, eg to get conflicts with leaves:
```java
client.getDocument(
                new GetDocumentOptions.Builder("db", docid).conflicts(true).openRevs(List.of("all")).build()).execute();
```

the result is

```
Exception in thread "main" com.ibm.cloud.sdk.core.service.exception.InvalidServiceResponseException: Error processing the http response
	at com.ibm.cloud.sdk.core.service.BaseService.processServiceCall(BaseService.java:383)
	at com.ibm.cloud.sdk.core.service.BaseService$IBMCloudSDKServiceCall.execute(BaseService.java:441)
	at Utils.causeConflict(Utils.java:70)
	at Utils.main(Utils.java:33)
Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at line 1 column 2 path $
	at com.ibm.cloud.sdk.core.util.DynamicModelTypeAdapterFactory$Adapter.read(DynamicModelTypeAdapterFactory.java:437)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	at com.ibm.cloud.sdk.core.util.ResponseUtils.getValue(ResponseUtils.java:149)
	at com.ibm.cloud.sdk.core.util.ResponseConverterUtils$6.convert(ResponseConverterUtils.java:137)
	at com.ibm.cloud.sdk.core.service.BaseService.processServiceCall(BaseService.java:381)
	... 3 more
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at line 1 column 2 path $
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:386)
	at com.ibm.cloud.sdk.core.util.DynamicModelTypeAdapterFactory$Adapter.read(DynamicModelTypeAdapterFactory.java:409)
	... 7 more
```

Running the call with curl against couchdb gives a multipart response:
```
--c882f989a22171cc1c84999f16ec2073
Content-Type: application/json

{"_id":"2afaeb6d58bcf9eabfca418d7a004088","_rev":"2-23e0333412b354795df6c2c7b33b4739","data":"def"}
--c882f989a22171cc1c84999f16ec2073
Content-Type: application/json

{"_id":"2afaeb6d58bcf9eabfca418d7a004088","_rev":"2-4249ad050ca36950dba946302b15ef3a","data":"abc"}
--c882f989a22171cc1c84999f16ec2073--

```
**To Reproduce**
run the call above against a document with conflicts.

**Expected behavior**
The sdk should be able to parse the response and provide a list of the resulting documents or throw a more meaningful error if another method should be used

**Must gather (please complete the following information):**
 - SDK Version 0.0.22
 - Java Version 16
 - Name of service that you're trying to use (if applicable): couchdb 3.1.1

**Comment by ricellis** [comment]
https://github.com/IBM/cloudant-java-sdk/blob/master/KNOWN_ISSUES.md#cannot-request-all-open-revs

**Comment by vmatyusGitHub** [comment]
As a workaround you can use `getDocumentAsStream` request.
Its result will be an `InputStream` that should be parsed with any application of your choice.

In the following example I used Gson:
```java
GetDocumentOptions documentOptions =
        new GetDocumentOptions.Builder("db", "dicid")
                 .addOpenRevs("all")
                .build();

try(InputStream resultAsInputStream = examplesClient.getDocumentAsStream(documentOptions)
        .execute().getResult()){
    JsonElement resultAsJson = JsonParser.parseReader(new InputStreamReader(resultAsInputStream));
    JsonArray resultAsJsonArray = resultAsJson.getAsJsonArray();
    for (JsonElement e: resultAsJsonArray) {
        Document doc = GsonSingleton.getGson()
                .fromJson(e.getAsJsonObject().get("ok"), Document.class);
        System.out.println(doc);
    }
} catch (RuntimeException | IOException re){
    System.out.println("Exception occurred:" + re);
}
```

**Comment by mojito317** [comment]
Hi @thigg! 

Another workaround could be for `open_revs=all` to use the `_bulk_get` endpoint instead:
```java
...
BulkGetQueryDocument bulkGetQueryDocument = new BulkGetQueryDocument.Builder()
        .id(docId).build();

PostBulkGetOptions postBulkGetOptions = new PostBulkGetOptions.Builder()
        .db("db")
        .docs(Arrays.asList(bulkGetQueryDocument)).build();

BulkGetResult bulkGetResult = client
        .postBulkGet(postBulkGetOptions)
        .execute()
        .getResult();

List<BulkGetResultDocument> openRevs = bulkGetResult.getResults().get(0).getDocs();
```

From the `BulkGetResultDocument` you can wrap out the `Document` objects for example this way:
```java
List<Document> docs = new ArrayList<>();

openRevs.stream().forEach(doc -> {
   if (doc.getError() == null)
    docs.add(doc.getOk());
});
```
