### ISSUE TITLE
Add docs on how to log http requests for debugging

### ISSUE THREAD

**Issue by thigg** [IBM/cloudant-java-sdk#125]
Currently I'm facing a very helpful error:

```
Exception in thread "main" com.ibm.cloud.sdk.core.service.exception.InternalServerErrorException: error
	at com.ibm.cloud.sdk.core.service.BaseService.processServiceCall(BaseService.java:407)
	at com.ibm.cloud.sdk.core.service.BaseService$IBMCloudSDKServiceCall.execute(BaseService.java:441)

```

It would help, if it would be documented how you can log the request that caused this error.

An option for that would be to be able to add an okhhtp logging interceptor.

**Comment by eiri** [comment]
https://cloud.ibm.com/apidocs/cloudant?code=java#logging

**Comment by thigg** [comment]
shame on me, that was exactly what I was looking for.
