### ISSUE TITLE
An exception on parsing Cloudant http response to SearchResult object

### ISSUE THREAD

**Issue by junior-user** [IBM/cloudant-java-sdk#211]
**Describe the bug**

An exception `Expected BEGIN_OBJECT but was NUMBER at line 1 column 65 path $.counts` occurred on query a search index with `counts`, if search results has no findings.
```
Exception in thread "main" com.ibm.cloud.sdk.core.service.exception.InvalidServiceResponseException: Error processing the http response
	at com.ibm.cloud.sdk.core.service.BaseService.processServiceCall(BaseService.java:515)
	at com.ibm.cloud.sdk.core.service.BaseService$IBMCloudSDKServiceCall.execute(BaseService.java:573)
	at com.ibm.yourlearning.sandbox.Sandbox.main(Sandbox.java:45)
Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was NUMBER at line 1 column 65 path $.counts.
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
	at com.google.gson.Gson.fromJson(Gson.java:963)
	at com.ibm.cloud.sdk.core.util.ResponseUtils.getValue(ResponseUtils.java:149)
	at com.ibm.cloud.sdk.core.util.ResponseConverterUtils$6.convert(ResponseConverterUtils.java:137)
	at com.ibm.cloud.sdk.core.service.BaseService.processServiceCall(BaseService.java:513)
	... 2 more
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was NUMBER at line 1 column 65 path $.counts.
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:384)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:183)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:187)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	... 6 more
```

**To Reproduce**

1. Database "db_for_demo" must have the following design element (`updated` is indexed as `facet`;  `"analyzer": "keyword"` is used ):
```
{
  "_id": "_design/DDForDemo",
  "views": {},
  "language": "javascript",
  "indexes": {
    "IndexForDemo": {
      "analyzer": "keyword",
      "index": "function (doc) {\n    if (doc.updated && doc.parentId && doc.status === \"Active\") {\n        index(\"updated\", doc.updated);\n        index(\"parentId\", doc.parentId, {\n            \"index\": \"analyzed\",\n            \"facet\": true\n        });\n    }\n}\n"
    }
  }
}
```

2. Database "db_for_demo" must have at least one document included in index (has `updated`, `parentId`, and `status: "Active"`)
```
{
  "_id": "DEMO1",
  "status": "Active",
  "updated": "2021-01-19T13:21:13.215Z",
  "parentId": "PARENT_ID_ONE"
}
```

3. Perform a call to `postSearch` endpoint with the following parameters (use `addCounts`; document doesn't match query - in our case due to `updated` date the document will not be returned):

```
Cloudant service = Cloudant.newInstance();

PostSearchOptions searchOptions = new PostSearchOptions.Builder()
    .db("db_for_demo")
    .ddoc("DDForDemo")
    .index("IndexForDemo")
	.limit(0)
	.includeDocs(false)
	.addCounts("parentId")
    .query("updated:[2021-03-20T13:21:13.215Z TO Infinity]")
    .build();

Response<SearchResult> executeResonse =
	service.postSearch(searchOptions).execute();

System.out.println(executeResonse.getStatusCode());
```

**Expected behavior**

No exception;
executeResonse.getStatusCode() is 200 (OK)
executeResonse.getResult().getCounts().size() is 0

**Must gather (please complete the following information):**

 - SDK Version
com.ibm.cloud:cloudant:0.0.32
 - Java Version
```
 $ java -version
openjdk version "11.0.13" 2021-10-19
IBM Semeru Runtime Open Edition 11.0.13.0 (build 11.0.13+8)
Eclipse OpenJ9 VM 11.0.13.0 (build openj9-0.29.0, JRE 11 Windows 10 amd64-64-Bit Compressed References 20211022_218 (JIT enabled, AOT enabled)
OpenJ9   - e1e72c497
OMR      - 299b6a2d2
JCL      - 2d83aa3b76 based on jdk-11.0.13+8)
```
 - Name of service that you're trying to use (if applicable)
com.ibm.cloud:cloudant
- Name of operation that you're trying to invoke (if applicable) 
Cloudant::postSearch

**Additional context**

Please, note that Cloudant returns different response for following cases:
1. No documents in database, or no documents included in index.
(set `"status": "Draft"`, for example)
```
{
  "_id": "DEMO1",
  "status": "Draft",
  "updated": "2021-01-20T13:21:13.215Z",
  "parentId": "PARENT_ID_ONE"
}
```

```
/db_for_demo/_design/DDForDemo/_search/IndexForDemo?q=updated%3A%5B2021-03-20T13%3A21%3A13.215Z TO Infinity%5D&limit=0&includeDocs=false&counts=["parentId"]
```
```
{"total_rows":0,"bookmark":"g2o","rows":[]}
```

2. There is at least one document in the index, but nothing match to the query (it is the subject of the Issue)
```
{
  "_id": "DEMO1",
  "status": "Active",
  "updated": "2021-01-19T13:21:13.215Z",
  "parentId": "PARENT_ID_ONE"
}
```

```
/db_for_demo/_design/DDForDemo/_search/IndexForDemo?q=updated%3A%5B2021-03-20T13%3A21%3A13.215Z TO Infinity%5D&limit=0&includeDocs=false&counts=["parentId"]
```
```
{"total_rows":0,"bookmark":"g2o","rows":[],"counts":{"parentId":0.0}}
```

3. There is at least one document in the index, query result contain a few documents (change to `"updated": "2021-05-20T13:21:13.215Z"`)
```
{
  "_id": "DEMO1",
  "status": "Active",
  "updated": "2021-05-19T13:21:13.215Z",
  "parentId": "PARENT_ID_ONE"
}
```
```
/db_for_demo/_design/DDForDemo/_search/IndexForDemo?q=updated%3A%5B2021-03-20T13%3A21%3A13.215Z TO Infinity%5D&limit=0&includeDocs=false&counts=["parentId"]
```
```
{"total_rows":1,"bookmark":"g2o","rows":[],"counts":{"parentId":{"PARENT_ID_ONE":1.0}}}
```

**Comment by ricellis** [comment]
Thank you for the clear and thorough report.

The problem is indeed caused by the HTTP/JSON API response failing to conform to the SDK model in the "no match" case. Unfortunately, this is one of a few places (some others are noted in the [KNOWN_ISSUES](https://github.com/IBM/cloudant-java-sdk/blob/master/KNOWN_ISSUES.md)) where the CouchDB API is relaxed about types and does not operate smoothly with more strongly typed languages like Java.

We will look into what we can do to improve this.

In the meantime it should be possible to avoid the exception by using the `postSearchAsStream` method and taking the `InputStream` of the response directly; bypassing the deserialisation into the `SearchResult` model class.
This gives the option, for example, of deserialising the `counts` property into a more flexibly typed JSON specific structure (e.g. something like a GSON `JsonElement`) and checking the type of the property before using it.

**Comment by ricellis** [comment]
https://github.com/apache/couchdb/pull/4704 is a proposal to fix the API types in CouchDB.

**Comment by ricellis** [comment]
There is a server-side correction for this issue from Cloudant version [8442](https://cloud.ibm.com/docs/Cloudant?topic=Cloudant-classic-release-notes#Cloudant-sep1423).
