### ISSUE TITLE
java.lang.NoClassDefFoundError: com/google/gson/internal/reflect/ReflectionAccessor

### ISSUE THREAD

**Issue by NickKanellos** [IBM/cloudant-java-sdk#253]
**Describe the bug**
```
java.lang.NoClassDefFoundError: com/google/gson/internal/reflect/ReflectionAccessor
 at com.ibm.cloud.sdk.core.util.DynamicModelTypeAdapterFactory.(DynamicModelTypeAdapterFactory.java:77)
 at com.ibm.cloud.sdk.core.util.GsonSingleton.registerTypeAdapters(GsonSingleton.java:77)
 at com.ibm.cloud.sdk.core.util.GsonSingleton.createGson(GsonSingleton.java:53)
 at com.ibm.cloud.sdk.core.util.GsonSingleton.getGsonWithoutPrettyPrinting(GsonSingleton.java:102)
 at com.ibm.cloud.sdk.core.http.RequestBuilder.bodyContent(RequestBuilder.java:417)
 at com.ibm.cloud.cloudant.v1.Cloudant.postDocument(Cloudant.java:825)
```

**To Reproduce**
call `com.ibm.cloud.cloudant.v1.Cloudant.postDocument()` using 
```xml
<dependency>
     <groupId>com.ibm.cloud</groupId>
     <artifactId>cloudant-common</artifactId>
     <version>0.0.36</version>
</dependency>
```
and 
```xml
<!-- https://mvnrepository.com/artifact/com.google.code.gson/gson -->
<dependency>
    <groupId>com.google.code.gson</groupId>
    <artifactId>gson</artifactId>
    <version>2.9.0</version>
</dependency>
```
Unfortunately I can't use an earlier version of GSON because of this:
https://github.com/google/gson/issues/1875
and this
https://github.com/google/gson/pull/1902

**Must gather (please complete the following information):**
 ```
$ java --version
openjdk 16.0.2 2021-07-20
OpenJDK Runtime Environment Temurin-16.0.2+7 (build 16.0.2+7)
OpenJDK 64-Bit Server VM Temurin-16.0.2+7 (build 16.0.2+7, mixed mode, sharing)
```

**Additional context**

**Comment by ricellis** [comment]
You can track https://github.com/IBM/cloudant-java-sdk/pull/236 for our update to support GSON 2.9, we are waiting on a fix in https://github.com/IBM/java-sdk-core.

FWIW the GSON problems you link to are caused by changes in visibility to internal classes in Java 9+, that were _warnings_ prior to Java 16. This is exact reason why we declare support for running only on [Java 8 and 11](https://github.com/IBM/cloudant-java-sdk#prerequisites) currently.

It is possible to use this library with Java 16 and GSON 2.8.9 by supplying the JVM option to switch the error back to a warning or by breaking encapsulation - see https://github.com/IBM/java-sdk-core/issues/127#issuecomment-978069664. It is worth noting that Java 16 is not a maintained Java version anyway; in Java 17 the option to switch the error back to a warning has been removed and breaking encapsulation is the only workaround.

**Comment by NickKanellos** [comment]
@ricellis Excellent.  Thank you!
