### ISSUE TITLE
Exception at parsing /identity/token response

### ISSUE THREAD

**Issue by LenarBad** [IBM/cloudant-java-sdk#322]
**Describe the bug**
The client failed to parse a response for a call https://iam.cloud.ibm.com/identity/token - thrown a Gson exception

**To Reproduce**
 - Instantiate 
 ```java        
       IamAuthenticator authenticator = new IamAuthenticator.Builder()
                .apikey(cloudantApiKey)
                .build();
        Cloudant service = new Cloudant("Cloudant-5t", authenticator);
        service.setServiceUrl(cloudantUrl);
 ```
 - Make a call
 ```java
        ServerInformation serverInformation = cloudant
                .getServerInformation()
                .execute()
                .getResult();
```

**Expected behavior**
Expected - no exception thrown
Actual result - thrown a `java.lang.RuntimeException` (see the stacktrace below)

**Screenshots**
After some debug I found that the successful response was actually received (see the screenshot) but Gson failed to parse it
![image](https://user-images.githubusercontent.com/13533812/183308953-c88325bf-acdf-4da7-a9ca-7d764a9e48b5.png)

**Must gather (please complete the following information):**
 - SDK Version 0.2.0
 - Java Version 
 ```
 $ java -version
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
```

**Additional context**
```
java.lang.RuntimeException: Error while fetching access token from token service: 

	at com.ibm.cloud.sdk.core.security.TokenRequestBasedAuthenticator.getToken(TokenRequestBasedAuthenticator.java:272)
	at com.ibm.cloud.sdk.core.security.TokenRequestBasedAuthenticator.authenticate(TokenRequestBasedAuthenticator.java:210)
	at com.ibm.cloud.sdk.core.service.BaseService.setAuthentication(BaseService.java:414)
	at com.ibm.cloud.sdk.core.service.BaseService.createCall(BaseService.java:352)
	at com.ibm.cloud.sdk.core.service.BaseService.createServiceCall(BaseService.java:390)
	at com.ibm.cloud.cloudant.internal.CloudantBaseService.createServiceCall(CloudantBaseService.java:185)
	at com.ibm.cloud.cloudant.v1.Cloudant.getServerInformation(Cloudant.java:223)
	at com.ibm.cloud.cloudant.v1.Cloudant.getServerInformation(Cloudant.java:236)
.....
Caused by: java.lang.NoClassDefFoundError: com/google/gson/ToNumberStrategy
	at com.ibm.cloud.sdk.core.util.ResponseUtils.getValue(ResponseUtils.java:149)
	at com.ibm.cloud.sdk.core.util.ResponseConverterUtils$6.convert(ResponseConverterUtils.java:137)
	at com.ibm.cloud.sdk.core.security.TokenRequestBasedAuthenticator$2.run(TokenRequestBasedAuthenticator.java:323)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: com.google.gson.ToNumberStrategy
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 4 more
```

**Comment by ricellis** [comment]
`Caused by: java.lang.NoClassDefFoundError: com/google/gson/ToNumberStrategy`

IIRC that class was added since GSON 2.8.9. 

cloudant-java-sdk@0.2.0 asks for GSON 2.9.0†.

Please make sure you have the correct version of GSON on your classpath or that another requirement isn't putting an older version of GSON earlier on the classpath.

†[here](https://github.com/IBM/cloudant-java-sdk/blob/3432643b83605fa52c3ab69299f0748737ac4e33/modules/cloudant/pom.xml#L52) and via [IBM Cloud sdk-core@9.17.3](https://github.com/IBM/cloudant-java-sdk/blob/3432643b83605fa52c3ab69299f0748737ac4e33/pom.xml#L18) dependency [here](https://github.com/IBM/java-sdk-core/blob/0bbb8f1a7c736ac899cb3b7ebe2db2b084366e4c/pom.xml#L21).

**Comment by LenarBad** [comment]
Yes, that was the issue.
I think it's worth mentioning somewhere.
Anyway thank you!
